src/compositor/windowpixmapitem.cpp
The user of WindowPixmapItem should delete it.
=> [lipstick] Don't delete the WindowPixmapItems on surface destruction

src/components/launcherdbus.cpp, src/components/launcherdbus.h, src/components/launcherfoldermodel.cpp, src/components/launcherfoldermodel.h, src/components/launchermodel.cpp, src/components/launchermodel.h
The purpose of this is to show feedback to the user when he starts an app in a way which doesn't directly involve the compositor.
See https://github.com/nemomobile/mapplauncherd/pull/28
=> [lipstick] Add a DBus method to notify an app is starting

protocol/lipstick-recorder.xml, src/compositor/compositor.pri, src/compositor/lipstickcompositor.cpp, src/compositor/lipstickcompositor.h, src/compositor/lipstickrecorder.cpp, src/compositor/lipstickrecorder.h, tests/stubs/lipstickcompositor_stub.h
This PR adds a protocol allowing an external client to ask lipstick to record and pass frames to it. The client can then save them to file, send them remotely, make a video...
There are a couple of open questions still: should we restrict the lipstick_recorder global to only some clients? If so, how? Should we show something on screen when it's recording?
=> Add a wayland interface to record the screen

tests/ut_devicelock/ut_devicelock.cpp
Devicelock added Undefined-check fix a while back which broke this test. So fixing the test to check transition from Locked-state to Unlocked-state.
=> [lipstick] Fix devicelock tests to correspond with latest changes

src/compositor/lipstickcompositor.cpp
Without proper QObject parent, windows might get deleted
by garbage collector.
=> [lipstick] Make sure LCWs are not gc()d

src/notifications/lipsticknotification.cpp, src/notifications/lipsticknotification.h, src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h, tests/stubs/notificationmanager_stub.h, tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp, tests/ut_notificationmanager/ut_notificationmanager.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
This property allows clients to indicate the origin of a notification
to the manager.  The interpretation of this property is left to
the notification manager.
=> [lipstick] Extend notifications with 'origin' property

src/homeapplication.cpp, src/volume/volumecontrol.cpp, src/volume/volumecontrol.h
Make volume settable from QML. Add volume control as a global context
property so that it is available before the volume control window is
constructed.
=> [lipstick] Add API for setting volume from QML.

plugin/lipstickplugin.cpp, plugin/plugin.pro, src/compositor/compositor.pri, src/compositor/hwcimage.cpp, src/compositor/hwcimage.h, src/compositor/hwcinterface.h, src/compositor/hwcrenderstage.cpp, src/compositor/hwcrenderstage.h, src/compositor/lipstickcompositor.cpp, src/compositor/lipstickcompositorwindow.cpp
On the rendering thread in lipstick, we install a custom scene graph
rendering stage. In this stage, we look through the scene graph for
hardware compatible nodes and put these into their own block.
We're currently only supporting in-process images (for background
images) without rotation (for now) and no scaling. The custom render
stage will look at the transform of these images and decide if it can
be sent to the hwc or not.
We can talk to the hwc using an abstraction API called HwcInterface
which we can query from the QPA plugin. The API is located in
'hwcinterface.h' and is a direct copy of the same file inside
the QPA plugin. It has been done like this to have some API
while keeping this out of the public API. There is a version
name string to prevent mismatches between the plugin …
=> [lipstick[ Implement basic hardware compositor support in lipstick.

src/compositor/hwcimage.cpp, src/compositor/hwcrenderstage.cpp
We had two potential bugs:
1. QQuickItem::rotation() didn't wrap at 0 and 360 degrees, so we failed the
check for rotations such as -90 and 450.
2. The check for translation-only matrix relied on optimize() and the
translate bit of QMatrix4x4 which can easily fail due to accululated
floating point errors in the matrix. Make the test a lot coarser.
=> [lipstick] Make sure we catch 90 degree rotations properly

src/compositor/windowpixmapitem.cpp, src/compositor/windowpixmapitem.h
These complement xScale and yScale and allow the scaled content to be
positioned.
=> [lipstick] Add xOffset and yOffset properties to WindowPixmapItem.

src/components/launcheritem.cpp, src/components/launcheritem.h, src/components/launchermodel.cpp
If isLaunching was set true by launchApplication it would be reset
after 5 seconds to allow for failed starts.  Extend this protection
to all means of setting isLaunching.
=> [lipstick] Always clear LauncherItem.isLaunching after a set timeout.

src/notificationcategories/device.added.conf, src/notificationcategories/device.conf, src/notificationcategories/device.error.conf, src/notificationcategories/device.removed.conf, src/notificationcategories/network.conf, src/notificationcategories/network.connected.conf, src/notificationcategories/network.disconnected.conf, src/notificationcategories/network.error.conf, src/notificationcategories/x-nemo.battery.chargingcomplete.conf, src/notificationcategories/x-nemo.battery.chargingnotstarted.conf, src/notificationcategories/x-nemo.battery.conf, src/notificationcategories/x-nemo.battery.enterpsm.conf, src/notificationcategories/x-nemo.battery.exitpsm.conf, src/notificationcategories/x-nemo.battery.lowbattery.conf, src/notificationcategories/x-nemo.battery.notenoughpower.conf, src/notificationcategories/x-nemo.battery.recharge.conf, src/notificationcategories/x-nemo.battery.removecharger.conf, src/notificationcategories/x-nemo.battery.shutdown.conf, src/notificationcategories/x-nemo.battery.temperature.conf, src/notificationcategories/x-nemo.connectionselector.cellular.conf, src/notificationcategories/x-nemo.connectionselector.wifi.conf, src/notificationcategories/x-nemo.device.locked.conf, src/notificationcategories/x-nemo.diskspace.low.conf, src/notificationcategories/x-nemo.system.diskspace.conf
'urgency=2' is no longer required for notifications to be automatically removed after display, instead use 'expireTimeout=0'.
Depends on: https://github.com/nemomobile/lipstick/pull/250
=> [lipstick] Adjust urgency and expiry values for system notification categories

src/notifications/notificationmanager.cpp, src/notifications/notificationpreviewpresenter.cpp, tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.h
Rather than automatically closing notifications with Critical urgency, mark them as displayed so that their expiry timeout can take effect.
=> Trigger notification expiry

src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h
If a notification does not specify the name or icon associated with the originating application, attempt to determine the values by inspecting the desktop file associated with the PID from which the notification was dispatched.
=> [lipstick] Look up notification app properties by PID

src/notifications/lipsticknotification.cpp, src/notifications/lipsticknotification.h, src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h, tests/stubs/notificationmanager_stub.h, tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
Record the ownership of notifications explcitily to facilitate the Notification::notifications() accessor provided by nemo-qml-plugin-notifications, without requiring the appName property to have a default value.
This allows us to add a default appName value to the notifications if one is not provided.
=> [lipstick] Separate ownership from appName property

rpm/lipstick-qt5.spec, src/compositor/windowpixmapitem.cpp, src/compositor/windowpixmapitem.h
When the surface being used by a WindowPixmapItem gets a NULL buffer
make a screenshot of it, scaled down to the size of the WindowPixmapItem,
and only then release the last wayland buffer.
This makes sure we won't be showing random content due to the current NULL buffer attached.
Needs https://github.com/mer-qt/qtwayland/pull/26
=> [lipstick] Make a screenshot of the WindowPixmanItem's surface when hidden

src/compositor/lipstickcompositorwindow.cpp, src/compositor/lipstickcompositorwindow.h
Ensure touchs are canceled when the item's window changes, and verify
the window() pointer before dereferencing it.
=> [lipstick] Fix crash when a compositor window is removed from the scene.

src/notifications/notificationmanager.cpp
If a notification originating in an Android environment is forwarded to lipstick with the 'appName' property as 'AndroidNotification', replace that name with the Android application name, which should be the 'summary' property.
=> [lipstick] Translate Android notification appName property

src/notifications/notificationmanager.cpp
The directory is always relative to the home directory of the nemo user, not the effective user.
=> [lipstick] Fix notifications DB directory

src/compositor/lipstickcompositor.h, src/compositor/lipstickcompositorprocwindow.cpp, src/homewindow.cpp
Setting it after the fact meant the property wasn't initialized until after
windowAdded was emitted and therefore couldn't be used in that handler.
=> [lipstick] Pass the rootItem as an argument to mapProcWindow.

src/notificationcategories/x-nemo.diskspace.low.conf, src/notificationcategories/x-nemo.system.diskspace.conf, src/notifications/diskspacenotifier.cpp, src/notifications/notificationlistmodel.cpp, tests/ut_diskspacenotifier/ut_diskspacenotifier.cpp, tests/ut_notificationlistmodel/ut_notificationlistmodel.cpp, tests/ut_notificationlistmodel/ut_notificationlistmodel.h
Use only a single notification for diskspace warnings, and ensure it is correctly visible from the events view.
=> Unify diskspace notifications

src/compositor/lipstickcompositor.cpp, src/compositor/lipstickcompositor.h, src/homeapplication.cpp, tests/stubs/lipstickcompositor_stub.h
Rendering is supressed (updates enabled false) until MCE allows updates.
When single shot timer is triggered we register compositor
to dbus, create QmDisplayState instance, set initial state, and
connect signals.
MCE sends setUpdatesEnabled to compositor when we can start rendering
(when "org.nemomobile.compositor" gets registered).
=> [lipstick] Create display related component after compositor created.

src/notificationcategories/device.added.conf, src/notificationcategories/device.removed.conf, src/notificationcategories/x-nemo.battery.chargingcomplete.conf, src/notificationcategories/x-nemo.battery.conf, src/notificationcategories/x-nemo.battery.enterpsm.conf, src/notificationcategories/x-nemo.battery.exitpsm.conf, src/notificationcategories/x-nemo.battery.lowbattery.conf, src/notificationcategories/x-nemo.battery.notenoughpower.conf, src/notificationcategories/x-nemo.battery.removecharger.conf, src/notificationcategories/x-nemo.battery.temperature.conf, src/notificationcategories/x-nemo.connectionselector.cellular.conf, src/notificationcategories/x-nemo.connectionselector.wifi.conf, src/notificationcategories/x-nemo.device.locked.conf
Criticial urgency is required in order that these notifications are displayed even when the screen is locked.
=> [lipstick] Restore critical urgency level to some notifications. Contributes to MER#915

src/compositor/lipstickcompositorwindow.cpp, src/compositor/lipstickcompositorwindow.h
In order to better support transient windows, enable opt-in click-to-focus.
=> [lipstick] Focus on touch for selected surfaces. Contributes to JB#27230

src/utilities/qobjectlistmodel.cpp, tests/ut_launchermodel/ut_launchermodel.pro, tests/ut_notificationlistmodel/ut_notificationlistmodel.pro, tests/ut_qobjectlistmodel/ut_qobjectlistmodel.pro
QObject instances returned from Q_INVOKABLE functions become subject to garbage collection, unless explicitly protected.
=> [lipstick] Protect QObject instances from garbage collection. Contributes to MER#917

src/compositor/lipstickcompositor.cpp, src/compositor/lipstickcompositorwindow.cpp
qt_key has some flaws, it doesn't support changing the keymap and
breaks the wayland abstraction giving the clients the events that
come directly from the platform lipstick is running on.
=> [lipstick] Don't enable the qt_key wayland extension. Fixes MER#925

src/notifications/notificationmanager.cpp
The timestamps are treated as local unless flagged as UTC.
=> [lipstick] Correct notification timestamps at restore

src/notifications/notificationmanager.cpp
The timestamps are treated as local unless flagged as UTC.
=> [lipstick] Correct notification timestamps at restore. Contributes to MER#924

rpm/lipstick-qt5.spec
screenshottool is the only UI tool provided by this project, so the
name of the package is changed to better describe the content.
=> [lipstick] Move screenshottool to its own package

src/compositor/hwcrenderstage.cpp
A node which has an accumulative transform that is anything other than
a translation it is not hwcomposer compatible, return false in this
case instead of true.
=> [lipstick] Fix disappearing transformed HWC nodes.  Fixes MER#974

src/compositor/lipstickcompositor.cpp, src/compositor/lipstickcompositor.h, tests/stubs/lipstickcompositor_stub.h
For starters, did a simple workaround for QtWayland bug. I think it should protect against invalid layouts while allowing relevant ones.
(cc: @giucam)
=> [lipstick] Allow settings hardware keyboard layout with a property. Fixes MER#960

rpm/lipstick-qt5.spec, src/compositor/lipstickcompositorwindow.cpp
This reverts commit 1d1556fdcde6c81fe351e2a5e8825f738d43cd4e.
We now have the needed support in qtwayland.
[lipstick] Check the input region of surfaces. Contributes to MER#986
=> Revert "Revert "Merge pull request #236 from giucam/master""

src/notifications/notificationlistmodel.cpp, tests/ut_notificationlistmodel/ut_notificationlistmodel.cpp
The sorting function must provide a strict weak ordering depending on the properties of the sorted notifications independent of their current position in the list.  Use replacesId as the discriminator
when timestamp is equivalent.
Also, do not compare a notification to itself in the list, as the properties may have been updated since it was sorted into that position.
=> [lipstick] Ensure correct sorting of notifications. Contributes to MER#991

src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h
Lipstick with notification grouping is badly affected by the presence of large numbers of hidden notifications.  Remove any pre-existing notifications at startup to avoid this issue, unless the schema version indicates this has previously occurred.
=> [lipstick] Remove obsolete notifications. Contributes to MER#995

src/notifications/lipsticknotification.cpp
The appIcon property is used for notification grouping, which is not required for the 1.1.6 release series.
=> [lipstick] Do not return appIcon property. Contributes to MER#1012

src/usbmodeselector.h
USB modes hardcoded in USB selector QML component don't match the ones used by the C++ code. QML should use the constants provided by C++ to make sure that they do match.
=> Export USB modes to QML. Contributes to JB#15005

src/notifications/notificationmanager.cpp
When a notification with preview properties is received from Android, ensure that both preview body and preview summary are non-empty to select the appropriate banner type.
=> [lipstick] Sanitize Android notification preview properties. Contributes to MER#1034

src/compositor/lipstickcompositorwindow.cpp
Depends on https://github.com/mer-qt/qtdeclarative/pull/70 and https://github.com/mer-qt/qtbase/pull/40. 
This fixes the same bug as #297 but in a imho better way. We simply avoid sending mouse events to clients if the events are synthesized, this way the qtwayland state is kept sane.
=> Don't send synthesized mouse events to clients

src/notifications/notificationlistmodel.cpp, src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h, tests/ut_notificationmanager/ut_notificationmanager.cpp
Includes restructuring to allow timestamps to be corrected only on notification submission.
=> [lipstick] Correctly handle notification timestamps. Contributes to MER#1036

src/compositor/lipstickcompositor.cpp, src/compositor/lipstickcompositor.h, tests/stubs/lipstickcompositor_stub.h
We want to give the clients some time to stop drawing after the screen
goes blank, without blocking them.
=> Delay hiding the compositor window

src/components/launchermodel.cpp
**Primary problem:** For some packages that only install `/etc/xdg/autostart/<something>.desktop`, the store-client will notify the model about this file appearing. We then update the temporary icon for the in-progress installation with the new .desktop file name, and (as a consequence of the file actually existing) mark the icon as non-temporary.
**Primary fix:** Only accept .desktop file name changes if the .desktop file resides in one of the monitored directories where we expect application files ot be.
**Secondary problem:** If the .desktop file appears, but has its visibility set to `false`, lipstick won't update it if we change the .desktop filename without re-evaluating whether it should actually be shown. This is usually not a problem, because the visibility will be re-evaluated …
=> [launchermodel] Only accept .desktop files in monitored paths (Fixes JB#29427)

src/notifications/androidprioritystore.cpp
Notifications for interactive events such as messaging should have higher priority than email.  If Android notifications are selected for priority increase and have feedback associated with them, then give them a higher priority than email notifications.
=> [lipstick] Increase the priority of high-priority Android notifications. Contributes to MER#1059

src/notifications/notificationfeedbackplayer.cpp, src/notifications/notificationpreviewpresenter.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
Use the notification-specific function for turning on the display.
=> [lipstick] Use MCE to turn display on for notifications. Contributes to MER#1076

src/compositor/lipstickcompositorwindow.cpp
Check that pid is positive before trying to kill.
With some bad luck, lcw can belong to an application that does no
longer have a surface, or does not have a client, or the surface
is in the process of being destroyed. In those cases, it is possible
that trying to terminate the process would call kill with
pid 0 or -1.
=> [lipstick] Prevent lipstick from killing random apps. Fixes JB#29648

src/notifications/lipsticknotification.cpp, src/notifications/lipsticknotification.h, src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h, tests/stubs/notificationmanager_stub.h, tests/ut_lipsticknotification/ut_lipsticknotification.cpp, tests/ut_notificationfeedbackplayer/ut_notificationfeedbackplayer.cpp, tests/ut_notificationmanager/ut_notificationmanager.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
maxContentLines property can be used to indicate to the notification presenter how much content should be displayed for a specific notification.
=> [lipstick] Support maxContentLines notification hint. Contributes to MER#1055

src/androidnotificationpriorities
Notifications from 'Twitter messages' should not cause sound or LED feedback events.
=> [lipstick] Remove feedback from Twitter messages notifications. Contributes to MER#1035

src/utilities/qobjectlistmodel.cpp, tests/ut_qobjectlistmodel/ut_qobjectlistmodel.cpp
In the case of batch deletion, the rows reported as removed from the model are often not the ones actually removed.
=> [lipstick] Fix reporting of deleted model rows. Contributes to MER#1099

doc/src/notifications.dox, src/notifications/notificationmanager.cpp, tests/ut_notificationmanager/ut_notificationmanager.cpp
Default priority should be medium to allow notifications to specify a low relative priority if desired.
=> [lipstick] Default notification priority when unspecified. Contributes to MER#1118

src/compositor/lipstickcompositorwindow.cpp
When a touch event is ignored, it causes QtQuick to try a synthesized
mouse event. Disable event synthesis (checks internally for
Qt::LeftButton) to prevent entering zone of undefined behavior, as
Qt will keep on sending further touch events to the item, and we are
not ready to handle them.
This could be an issue in Qt -- touch events probably should not be
delivered to an item that accepted a synthesized mouse press.
=> [lipstick] Disable mouse event synthesis. Fixes JB#24350

doc/src/notifications.dox, src/notifications/notificationfeedbackplayer.cpp
Hidden notifications should not produce audible or vibratory feedback.
=> [lipstick] Suppress feedback from hidden notifications. Contributes to MER#1132

src/components/launchermodel.cpp, src/components/launchermodel.h
Ensure that ordered items are placed contiguously, and that unordered items are sorted by title rather than .desktop file name.
=> [lipstick] Fix initial launcher ordering. Contributes to MER#1146

src/homeapplication.cpp, src/lipsticksettings.cpp, src/lipsticksettings.h
This commit adds code to export the screen size width/height values
to dconf so that non-gui processes can access those values (e.g., to
determine optimal image sizes to sync).
Contributes to MER#1124
=> [lipstick] Export screen size as dconf keys. Contributes to MER#1124

src/notifications/notificationmanager.cpp
Alternative fix for
https://github.com/nemomobile/lipstick/pull/360
Worst offender was notifications[id] which as side-effect created a default constructed value on QHash.
Also noticed D-Bus handler missing a bit protection on input.
If good to go, I'll pick these to 1.1.9 too.
=> Fix notification crash

src/notifications/batterynotifier.cpp, src/notifications/batterynotifier.h
Do not notify on charging completion during maintenance charging cycles
Signed-off-by: Denis Zalevskiy <denis.zalevskiy@jolla.com>
=> [battery] Notify about charging completion only once. Fixes MER#1171

src/androidnotificationpriorities, src/notifications/androidprioritystore.cpp, src/notifications/androidprioritystore.h, src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h, tests/stubs/androidprioritystore_stub.h
The package name is not subject to localization, so prefer to identify Android notifications by that value rather than their human-readable name value.
=> [lipstick] Identify Android notifications by package name. Contributes to MER#1185

src/notifications/notificationmanager.cpp, src/notifications/notificationmanager.h, src/notifications/notificationpreviewpresenter.cpp, tests/ut_notificationmanager/ut_notificationmanager.cpp, tests/ut_notificationpreviewpresenter/ut_notificationpreviewpresenter.cpp
Updates to existing notifications are supposed to occur without the user being made aware of any changes.  Previews should be triggered only for initial publication of notifications.
=> [lipstick] Do not trigger preview when notification is updated. Contributes to MER#1187

src/notifications/lipsticknotification.cpp, src/notifications/lipsticknotification.h, src/notifications/notificationlistmodel.cpp
Store notification priority and timestamp values in optimal form for comparison, as comparison time dominates the cost of populating and maintaining notification models.
=> [lipstick] Cache notification values to optimize comparisons. Contributes to MER#1221

src/devicelock/devicelock.cpp
In a very long time ago activity signal only came after display state signal. But MCE has changed a while back to be async, and its possible that activity is true even when display is still off (as display can take ~300ms to wake up on some devices). This patch makes sure that lockTimer is only started when device is inactive (and not starting it when device is waking up).
=> [lipstick] devicelock triggers randomly. Fixes JB#31885

src/devicelock/devicelock.cpp, src/devicelock/devicelock.h
Emit the device lock state change over dbus before updating the UI
so that MCE is in the correct state before there is any attempt to
unlock the screen.
=> [lipstick] Fix device unlock sequence. Fixes JB#31285
